<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\AnswersOptions;
use App\Question;

class AnswersOptionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("answers_options")->insert([ "id" => "1", "name" => "Arquitectura", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "2", "name" => "Contador Público", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "3", "name" => "Ingeniería Industrial", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "4", "name" => "Ingeniería de Sistemas", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "5", "name" => "Ingeniería en Agronomía", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "6", "name" => "Ingeniería en Desarrollo Comunitario", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "7", "name" => "Ingeniería en Administración", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "8", "name" => "Ingeniería Informática", "question_id" => " 6", ]);
        DB::table("answers_options")->insert([ "id" => "9", "name" => "Masculino", "question_id" => " 8", ]);
        DB::table("answers_options")->insert([ "id" => "10", "name" => "Femenino", "question_id" => " 8", ]);
        //DB::table("answers_options")->insert([ "id" => "11", "name" => "No binario", "question_id" => " 8", ]);
        DB::table("answers_options")->insert([ "id" => "12", "name" => "Soltero", "question_id" => " 10", ]);
        DB::table("answers_options")->insert([ "id" => "13", "name" => "Casado", "question_id" => " 10", ]);
        DB::table("answers_options")->insert([ "id" => "14", "name" => "Sí", "question_id" => " 11", ]);
        DB::table("answers_options")->insert([ "id" => "15", "name" => "No", "question_id" => " 11", ]);
        DB::table("answers_options")->insert([ "id" => "16", "name" => "Casa", "question_id" => " 17", ]);
        DB::table("answers_options")->insert([ "id" => "17", "name" => "Departamento", "question_id" => " 17", ]);
        DB::table("answers_options")->insert([ "id" => "18", "name" => "Propia", "question_id" => " 18", ]);
        DB::table("answers_options")->insert([ "id" => "19", "name" => "Rentada", "question_id" => " 18", ]);
        DB::table("answers_options")->insert([ "id" => "20", "name" => "Prestada", "question_id" => " 18", ]);
        DB::table("answers_options")->insert([ "id" => "21", "name" => "Sí", "question_id" => " 22", ]);
        DB::table("answers_options")->insert([ "id" => "22", "name" => "No", "question_id" => " 22", ]);
        DB::table("answers_options")->insert([ "id" => "23", "name" => "Sí", "question_id" => " 28", ]);
        DB::table("answers_options")->insert([ "id" => "24", "name" => "No", "question_id" => " 28", ]);
        DB::table("answers_options")->insert([ "id" => "25", "name" => "Femenino", "question_id" => " 34", ]);
        DB::table("answers_options")->insert([ "id" => "26", "name" => "Masculino", "question_id" => " 34", ]);
        DB::table("answers_options")->insert([ "id" => "27", "name" => "Primaria", "question_id" => " 35", ]);
        DB::table("answers_options")->insert([ "id" => "28", "name" => "Secundaria", "question_id" => " 35", ]);
        DB::table("answers_options")->insert([ "id" => "29", "name" => "Preparatoria", "question_id" => " 35", ]);
        DB::table("answers_options")->insert([ "id" => "30", "name" => "Universidad", "question_id" => " 35", ]);
        DB::table("answers_options")->insert([ "id" => "31", "name" => "Titulo", "question_id" => " 35", ]);
        DB::table("answers_options")->insert([ "id" => "32", "name" => "Femenino", "question_id" => " 38", ]);
        DB::table("answers_options")->insert([ "id" => "33", "name" => "Masculino", "question_id" => " 38", ]);
        DB::table("answers_options")->insert([ "id" => "34", "name" => "Primaria", "question_id" => " 39", ]);
        DB::table("answers_options")->insert([ "id" => "35", "name" => "Secundaria", "question_id" => " 39", ]);
        DB::table("answers_options")->insert([ "id" => "36", "name" => "Preparatoria", "question_id" => " 39", ]);
        DB::table("answers_options")->insert([ "id" => "37", "name" => "Universidad", "question_id" => " 39", ]);
        DB::table("answers_options")->insert([ "id" => "38", "name" => "Titulo", "question_id" => " 39", ]);
        DB::table("answers_options")->insert([ "id" => "39", "name" => "Femenino", "question_id" => " 42", ]);
        DB::table("answers_options")->insert([ "id" => "40", "name" => "Masculino", "question_id" => " 42", ]);
        DB::table("answers_options")->insert([ "id" => "41", "name" => "Primaria", "question_id" => " 43", ]);
        DB::table("answers_options")->insert([ "id" => "42", "name" => "Secundaria", "question_id" => " 43", ]);
        DB::table("answers_options")->insert([ "id" => "43", "name" => "Preparatoria", "question_id" => " 43", ]);
        DB::table("answers_options")->insert([ "id" => "44", "name" => "Universidad", "question_id" => " 43", ]);
        DB::table("answers_options")->insert([ "id" => "45", "name" => "Titulo", "question_id" => " 43", ]);
        DB::table("answers_options")->insert([ "id" => "46", "name" => "Femenino", "question_id" => " 46", ]);
        DB::table("answers_options")->insert([ "id" => "47", "name" => "Masculino", "question_id" => " 46", ]);
        DB::table("answers_options")->insert([ "id" => "48", "name" => "Primaria", "question_id" => " 47", ]);
        DB::table("answers_options")->insert([ "id" => "49", "name" => "Secundaria", "question_id" => " 47", ]);
        DB::table("answers_options")->insert([ "id" => "50", "name" => "Preparatoria", "question_id" => " 47", ]);
        DB::table("answers_options")->insert([ "id" => "51", "name" => "Universidad", "question_id" => " 47", ]);
        DB::table("answers_options")->insert([ "id" => "52", "name" => "Titulo", "question_id" => " 47", ]);
        DB::table("answers_options")->insert([ "id" => "53", "name" => "Femenino", "question_id" => " 50", ]);
        DB::table("answers_options")->insert([ "id" => "54", "name" => "Masculino", "question_id" => " 50", ]);
        DB::table("answers_options")->insert([ "id" => "55", "name" => "Primaria", "question_id" => " 51", ]);
        DB::table("answers_options")->insert([ "id" => "56", "name" => "Secundaria", "question_id" => " 51", ]);
        DB::table("answers_options")->insert([ "id" => "57", "name" => "Preparatoria", "question_id" => " 51", ]);
        DB::table("answers_options")->insert([ "id" => "58", "name" => "Universidad", "question_id" => " 51", ]);
        DB::table("answers_options")->insert([ "id" => "59", "name" => "Titulo", "question_id" => " 51", ]);
        DB::table("answers_options")->insert([ "id" => "60", "name" => "Frecuente/M", "question_id" => " 57", ]);
        DB::table("answers_options")->insert([ "id" => "61", "name" => "Muy frecuente/M", "question_id" => " 57", ]);
        DB::table("answers_options")->insert([ "id" => "62", "name" => "Nunca", "question_id" => " 57", ]);
        DB::table("answers_options")->insert([ "id" => "63", "name" => "Antes", "question_id" => " 57", ]);
        DB::table("answers_options")->insert([ "id" => "64", "name" => "A veces", "question_id" => " 57", ]);
        DB::table("answers_options")->insert([ "id" => "65", "name" => "Frecuente/M", "question_id" => " 58", ]);
        DB::table("answers_options")->insert([ "id" => "66", "name" => "Muy frecuente/M", "question_id" => " 58", ]);
        DB::table("answers_options")->insert([ "id" => "67", "name" => "Nunca", "question_id" => " 58", ]);
        DB::table("answers_options")->insert([ "id" => "68", "name" => "Antes", "question_id" => " 58", ]);
        DB::table("answers_options")->insert([ "id" => "69", "name" => "A veces", "question_id" => " 59", ]);
        DB::table("answers_options")->insert([ "id" => "70", "name" => "Frecuente/M", "question_id" => " 60", ]);
        DB::table("answers_options")->insert([ "id" => "71", "name" => "Muy frecuente/M", "question_id" => " 60", ]);
        DB::table("answers_options")->insert([ "id" => "72", "name" => "Nunca", "question_id" => " 60", ]);
        DB::table("answers_options")->insert([ "id" => "73", "name" => "Antes", "question_id" => " 60", ]);
        DB::table("answers_options")->insert([ "id" => "74", "name" => "A veces", "question_id" => " 60", ]);
        DB::table("answers_options")->insert([ "id" => "75", "name" => "Frecuente/M", "question_id" => " 61", ]);
        DB::table("answers_options")->insert([ "id" => "76", "name" => "Muy frecuente/M", "question_id" => " 61", ]);
        DB::table("answers_options")->insert([ "id" => "77", "name" => "Nunca", "question_id" => " 61", ]);
        DB::table("answers_options")->insert([ "id" => "78", "name" => "Antes", "question_id" => " 61", ]);
        DB::table("answers_options")->insert([ "id" => "79", "name" => "A veces", "question_id" => " 61", ]);
        DB::table("answers_options")->insert([ "id" => "80", "name" => "Frecuente/M", "question_id" => " 62", ]);
        DB::table("answers_options")->insert([ "id" => "81", "name" => "Muy frecuente/M", "question_id" => " 62", ]);
        DB::table("answers_options")->insert([ "id" => "82", "name" => "Nunca", "question_id" => " 62", ]);
        DB::table("answers_options")->insert([ "id" => "83", "name" => "Antes", "question_id" => " 62", ]);
        DB::table("answers_options")->insert([ "id" => "84", "name" => "A veces", "question_id" => " 62", ]);
        DB::table("answers_options")->insert([ "id" => "85", "name" => "Frecuente/M", "question_id" => " 63", ]);
        DB::table("answers_options")->insert([ "id" => "86", "name" => "Muy frecuente/M", "question_id" => " 63", ]);
        DB::table("answers_options")->insert([ "id" => "87", "name" => "Nunca", "question_id" => " 63", ]);
        DB::table("answers_options")->insert([ "id" => "88", "name" => "Antes", "question_id" => " 63", ]);
        DB::table("answers_options")->insert([ "id" => "89", "name" => "A veces", "question_id" => " 63", ]);
        DB::table("answers_options")->insert([ "id" => "90", "name" => "Frecuente/M", "question_id" => " 64", ]);
        DB::table("answers_options")->insert([ "id" => "91", "name" => "Muy frecuente/M", "question_id" => " 64", ]);
        DB::table("answers_options")->insert([ "id" => "92", "name" => "Nunca", "question_id" => " 64", ]);
        DB::table("answers_options")->insert([ "id" => "93", "name" => "Antes", "question_id" => " 64", ]);
        DB::table("answers_options")->insert([ "id" => "94", "name" => "A veces", "question_id" => " 64", ]);
        DB::table("answers_options")->insert([ "id" => "95", "name" => "Frecuente/M", "question_id" => " 65", ]);
        DB::table("answers_options")->insert([ "id" => "96", "name" => "Muy frecuente/M", "question_id" => " 65", ]);
        DB::table("answers_options")->insert([ "id" => "97", "name" => "Nunca", "question_id" => " 65", ]);
        DB::table("answers_options")->insert([ "id" => "98", "name" => "Antes", "question_id" => " 65", ]);
        DB::table("answers_options")->insert([ "id" => "99", "name" => "A veces", "question_id" => " 65", ]);
        DB::table("answers_options")->insert([ "id" => "100", "name" => "Frecuente/M", "question_id" => " 66", ]);
        DB::table("answers_options")->insert([ "id" => "101", "name" => "Muy frecuente/M", "question_id" => " 66", ]);
        DB::table("answers_options")->insert([ "id" => "102", "name" => "Nunca", "question_id" => " 66", ]);
        DB::table("answers_options")->insert([ "id" => "103", "name" => "Antes", "question_id" => " 66", ]);
        DB::table("answers_options")->insert([ "id" => "104", "name" => "A veces", "question_id" => " 66", ]);
        DB::table("answers_options")->insert([ "id" => "105", "name" => "Frecuente/M", "question_id" => " 67", ]);
        DB::table("answers_options")->insert([ "id" => "106", "name" => "Muy frecuente/M", "question_id" => " 67", ]);
        DB::table("answers_options")->insert([ "id" => "107", "name" => "Nunca", "question_id" => " 67", ]);
        DB::table("answers_options")->insert([ "id" => "108", "name" => "Antes", "question_id" => " 67", ]);
        DB::table("answers_options")->insert([ "id" => "109", "name" => "A veces", "question_id" => " 67", ]);
        DB::table("answers_options")->insert([ "id" => "110", "name" => "Frecuente/M", "question_id" => " 68", ]);
        DB::table("answers_options")->insert([ "id" => "111", "name" => "Muy frecuente/M", "question_id" => " 68", ]);
        DB::table("answers_options")->insert([ "id" => "112", "name" => "Nunca", "question_id" => " 68", ]);
        DB::table("answers_options")->insert([ "id" => "113", "name" => "Antes", "question_id" => " 68", ]);
        DB::table("answers_options")->insert([ "id" => "114", "name" => "A veces", "question_id" => " 68", ]);
        DB::table("answers_options")->insert([ "id" => "115", "name" => "Sí", "question_id" => " 70", ]);
        DB::table("answers_options")->insert([ "id" => "116", "name" => "No", "question_id" => " 70", ]);
        DB::table("answers_options")->insert([ "id" => "117", "name" => "Muy buena", "question_id" => " 77", ]);
        DB::table("answers_options")->insert([ "id" => "118", "name" => "Buena", "question_id" => " 77", ]);
        DB::table("answers_options")->insert([ "id" => "119", "name" => "Más o menos", "question_id" => " 77", ]);
        DB::table("answers_options")->insert([ "id" => "120", "name" => "Mala", "question_id" => " 77", ]);
        DB::table("answers_options")->insert([ "id" => "121", "name" => "Muy mala", "question_id" => " 77", ]);
        DB::table("answers_options")->insert([ "id" => "122", "name" => "Muy buena", "question_id" => " 78", ]);
        DB::table("answers_options")->insert([ "id" => "123", "name" => "Buena", "question_id" => " 78", ]);
        DB::table("answers_options")->insert([ "id" => "124", "name" => "Más o menos", "question_id" => " 78", ]);
        DB::table("answers_options")->insert([ "id" => "125", "name" => "Mala", "question_id" => " 78", ]);
        DB::table("answers_options")->insert([ "id" => "126", "name" => "Muy mala", "question_id" => " 78", ]);
        DB::table("answers_options")->insert([ "id" => "127", "name" => "Muy buena", "question_id" => " 79", ]);
        DB::table("answers_options")->insert([ "id" => "128", "name" => "Buena", "question_id" => " 79", ]);
        DB::table("answers_options")->insert([ "id" => "129", "name" => "Más o menos", "question_id" => " 79", ]);
        DB::table("answers_options")->insert([ "id" => "130", "name" => "Mala", "question_id" => " 79", ]);
        DB::table("answers_options")->insert([ "id" => "131", "name" => "Muy mala", "question_id" => " 79", ]);
        DB::table("answers_options")->insert([ "id" => "132", "name" => "Muy buena", "question_id" => " 80", ]);
        DB::table("answers_options")->insert([ "id" => "133", "name" => "Buena", "question_id" => " 80", ]);
        DB::table("answers_options")->insert([ "id" => "134", "name" => "Más o menos", "question_id" => " 80", ]);
        DB::table("answers_options")->insert([ "id" => "135", "name" => "Mala", "question_id" => " 80", ]);
        DB::table("answers_options")->insert([ "id" => "136", "name" => "Muy mala", "question_id" => " 80", ]);
        DB::table("answers_options")->insert([ "id" => "137", "name" => "Muy buena", "question_id" => " 81", ]);
        DB::table("answers_options")->insert([ "id" => "138", "name" => "Buena", "question_id" => " 81", ]);
        DB::table("answers_options")->insert([ "id" => "139", "name" => "Más o menos", "question_id" => " 81", ]);
        DB::table("answers_options")->insert([ "id" => "140", "name" => "Mala", "question_id" => " 81", ]);
        DB::table("answers_options")->insert([ "id" => "141", "name" => "Muy mala", "question_id" => " 81", ]);
        DB::table("answers_options")->insert([ "id" => "142", "name" => "Muy buena", "question_id" => " 82", ]);
        DB::table("answers_options")->insert([ "id" => "143", "name" => "Buena", "question_id" => " 82", ]);
        DB::table("answers_options")->insert([ "id" => "144", "name" => "Más o menos", "question_id" => " 82", ]);
        DB::table("answers_options")->insert([ "id" => "145", "name" => "Mala", "question_id" => " 82", ]);
        DB::table("answers_options")->insert([ "id" => "146", "name" => "Muy mala", "question_id" => " 82", ]);
        DB::table("answers_options")->insert([ "id" => "147", "name" => "Muy buena", "question_id" => " 83", ]);
        DB::table("answers_options")->insert([ "id" => "148", "name" => "Buena", "question_id" => " 83", ]);
        DB::table("answers_options")->insert([ "id" => "149", "name" => "Más o menos", "question_id" => " 83", ]);
        DB::table("answers_options")->insert([ "id" => "150", "name" => "Mala", "question_id" => " 83", ]);
        DB::table("answers_options")->insert([ "id" => "151", "name" => "Muy mala", "question_id" => " 83", ]);
        DB::table("answers_options")->insert([ "id" => "152", "name" => "Muy buena", "question_id" => " 84", ]);
        DB::table("answers_options")->insert([ "id" => "153", "name" => "Buena", "question_id" => " 84", ]);
        DB::table("answers_options")->insert([ "id" => "154", "name" => "Más o menos", "question_id" => " 84", ]);
        DB::table("answers_options")->insert([ "id" => "155", "name" => "Mala", "question_id" => " 84", ]);
        DB::table("answers_options")->insert([ "id" => "156", "name" => "Muy mala", "question_id" => " 84", ]);
        DB::table("answers_options")->insert([ "id" => "157", "name" => "Muy buena", "question_id" => " 85", ]);
        DB::table("answers_options")->insert([ "id" => "158", "name" => "Buena", "question_id" => " 85", ]);
        DB::table("answers_options")->insert([ "id" => "159", "name" => "Más o menos", "question_id" => " 85", ]);
        DB::table("answers_options")->insert([ "id" => "160", "name" => "Mala", "question_id" => " 85", ]);
        DB::table("answers_options")->insert([ "id" => "161", "name" => "Muy mala", "question_id" => " 85", ]);
        DB::table("answers_options")->insert([ "id" => "162", "name" => "Muy buena", "question_id" => " 86", ]);
        DB::table("answers_options")->insert([ "id" => "163", "name" => "Buena", "question_id" => " 86", ]);
        DB::table("answers_options")->insert([ "id" => "164", "name" => "Más o menos", "question_id" => " 86", ]);
        DB::table("answers_options")->insert([ "id" => "165", "name" => "Mala", "question_id" => " 86", ]);
        DB::table("answers_options")->insert([ "id" => "166", "name" => "Muy mala", "question_id" => " 86", ]);
        DB::table("answers_options")->insert([ "id" => "167", "name" => "Madre", "question_id" => " 87", ]);
        DB::table("answers_options")->insert([ "id" => "168", "name" => "Padre", "question_id" => " 87", ]);
        DB::table("answers_options")->insert([ "id" => "169", "name" => "Hermano", "question_id" => " 87", ]);
        DB::table("answers_options")->insert([ "id" => "170", "name" => "Otro", "question_id" => " 87", ]);
        DB::table("answers_options")->insert([ "id" => "171", "name" => "Madre", "question_id" => " 89", ]);
        DB::table("answers_options")->insert([ "id" => "172", "name" => "Padre", "question_id" => " 89", ]);
        DB::table("answers_options")->insert([ "id" => "173", "name" => "Tutor", "question_id" => " 89", ]);
        DB::table("answers_options")->insert([ "id" => "174", "name" => "Otro", "question_id" => " 89", ]);
        DB::table("answers_options")->insert([ "id" => "175", "name" => "Muy buena", "question_id" => " 92", ]);
        DB::table("answers_options")->insert([ "id" => "176", "name" => "Buena", "question_id" => " 92", ]);
        DB::table("answers_options")->insert([ "id" => "177", "name" => "Más o menos", "question_id" => " 92", ]);
        DB::table("answers_options")->insert([ "id" => "178", "name" => "Mala", "question_id" => " 92", ]);
        DB::table("answers_options")->insert([ "id" => "179", "name" => "Muy mala", "question_id" => " 92", ]);
        DB::table("answers_options")->insert([ "id" => "180", "name" => "Sí", "question_id" => " 95", ]);
        DB::table("answers_options")->insert([ "id" => "181", "name" => "No", "question_id" => " 95", ]);
        DB::table("answers_options")->insert([ "id" => "182", "name" => "Muy buena", "question_id" => " 96", ]);
        DB::table("answers_options")->insert([ "id" => "183", "name" => "Buena", "question_id" => " 96", ]);
        DB::table("answers_options")->insert([ "id" => "184", "name" => "Más o menos", "question_id" => " 96", ]);
        DB::table("answers_options")->insert([ "id" => "185", "name" => "Mala", "question_id" => " 96", ]);
        DB::table("answers_options")->insert([ "id" => "186", "name" => "Muy mala", "question_id" => " 96", ]);
        DB::table("answers_options")->insert([ "id" => "187", "name" => "Muy buena", "question_id" => " 97", ]);
        DB::table("answers_options")->insert([ "id" => "188", "name" => "Buena", "question_id" => " 97", ]);
        DB::table("answers_options")->insert([ "id" => "189", "name" => "Más o menos", "question_id" => " 97", ]);
        DB::table("answers_options")->insert([ "id" => "190", "name" => "Mala", "question_id" => " 97", ]);
        DB::table("answers_options")->insert([ "id" => "191", "name" => "Muy mala", "question_id" => " 97", ]);
        DB::table("answers_options")->insert([ "id" => "192", "name" => "No", "question_id" => " 100", ]);
        DB::table("answers_options")->insert([ "id" => "193", "name" => "Poco", "question_id" => " 100", ]);
        DB::table("answers_options")->insert([ "id" => "194", "name" => "Frecuente/M", "question_id" => " 101", ]);
        DB::table("answers_options")->insert([ "id" => "195", "name" => "Mucho", "question_id" => " 100", ]);
        DB::table("answers_options")->insert([ "id" => "196", "name" => "No", "question_id" => " 101", ]);
        DB::table("answers_options")->insert([ "id" => "197", "name" => "Poco", "question_id" => " 101", ]);
        DB::table("answers_options")->insert([ "id" => "198", "name" => "Frecuente/M", "question_id" => " 101", ]);
        DB::table("answers_options")->insert([ "id" => "199", "name" => "Mucho", "question_id" => " 101", ]);
        DB::table("answers_options")->insert([ "id" => "200", "name" => "No", "question_id" => " 102", ]);
        DB::table("answers_options")->insert([ "id" => "201", "name" => "Poco", "question_id" => " 102", ]);
        DB::table("answers_options")->insert([ "id" => "202", "name" => "Frecuente/M", "question_id" => " 102", ]);
        DB::table("answers_options")->insert([ "id" => "203", "name" => "Mucho", "question_id" => " 102", ]);
        DB::table("answers_options")->insert([ "id" => "204", "name" => "No", "question_id" => " 103", ]);
        DB::table("answers_options")->insert([ "id" => "205", "name" => "Poco", "question_id" => " 103", ]);
        DB::table("answers_options")->insert([ "id" => "206", "name" => "Frecuente/M", "question_id" => " 103", ]);
        DB::table("answers_options")->insert([ "id" => "207", "name" => "Mucho", "question_id" => " 103", ]);
        DB::table("answers_options")->insert([ "id" => "208", "name" => "No", "question_id" => " 104", ]);
        DB::table("answers_options")->insert([ "id" => "209", "name" => "Poco", "question_id" => " 104", ]);
        DB::table("answers_options")->insert([ "id" => "210", "name" => "Frecuente/M", "question_id" => " 104", ]);
        DB::table("answers_options")->insert([ "id" => "211", "name" => "Mucho", "question_id" => " 104", ]);
        DB::table("answers_options")->insert([ "id" => "212", "name" => "No", "question_id" => " 105", ]);
        DB::table("answers_options")->insert([ "id" => "213", "name" => "Poco", "question_id" => " 105", ]);
        DB::table("answers_options")->insert([ "id" => "214", "name" => "Frecuente/M", "question_id" => " 105", ]);
        DB::table("answers_options")->insert([ "id" => "215", "name" => "Mucho", "question_id" => " 105", ]);
        DB::table("answers_options")->insert([ "id" => "216", "name" => "No", "question_id" => " 106", ]);
        DB::table("answers_options")->insert([ "id" => "217", "name" => "Poco", "question_id" => " 106", ]);
        DB::table("answers_options")->insert([ "id" => "218", "name" => "Frecuente/M", "question_id" => " 106", ]);
        DB::table("answers_options")->insert([ "id" => "219", "name" => "Mucho", "question_id" => " 106", ]);
        DB::table("answers_options")->insert([ "id" => "220", "name" => "No", "question_id" => " 107", ]);
        DB::table("answers_options")->insert([ "id" => "221", "name" => "Poco", "question_id" => " 107", ]);
        DB::table("answers_options")->insert([ "id" => "222", "name" => "Frecuente/M", "question_id" => " 107", ]);
        DB::table("answers_options")->insert([ "id" => "223", "name" => "Mucho", "question_id" => " 107", ]);
        DB::table("answers_options")->insert([ "id" => "224", "name" => "No", "question_id" => " 108", ]);
        DB::table("answers_options")->insert([ "id" => "225", "name" => "Poco", "question_id" => " 108", ]);
        DB::table("answers_options")->insert([ "id" => "226", "name" => "Frecuente/M", "question_id" => " 108", ]);
        DB::table("answers_options")->insert([ "id" => "227", "name" => "Mucho", "question_id" => " 108", ]);
        DB::table("answers_options")->insert([ "id" => "228", "name" => "No", "question_id" => " 109", ]);
        DB::table("answers_options")->insert([ "id" => "229", "name" => "Poco", "question_id" => " 109", ]);
        DB::table("answers_options")->insert([ "id" => "230", "name" => "Frecuente/M", "question_id" => " 109", ]);
        DB::table("answers_options")->insert([ "id" => "231", "name" => "Mucho", "question_id" => " 109", ]);
        DB::table("answers_options")->insert([ "id" => "232", "name" => "No", "question_id" => " 110", ]);
        DB::table("answers_options")->insert([ "id" => "233", "name" => "Poco", "question_id" => " 110", ]);
        DB::table("answers_options")->insert([ "id" => "234", "name" => "Frecuente/M", "question_id" => " 110", ]);
        DB::table("answers_options")->insert([ "id" => "235", "name" => "Mucho", "question_id" => " 110", ]);
        DB::table("answers_options")->insert([ "id" => "236", "name" => "No", "question_id" => " 111", ]);
        DB::table("answers_options")->insert([ "id" => "237", "name" => "Poco", "question_id" => " 111", ]);
        DB::table("answers_options")->insert([ "id" => "238", "name" => "Frecuente/M", "question_id" => " 111", ]);
        DB::table("answers_options")->insert([ "id" => "239", "name" => "Mucho", "question_id" => " 111", ]);
        DB::table("answers_options")->insert([ "id" => "240", "name" => "No", "question_id" => " 112", ]);
        DB::table("answers_options")->insert([ "id" => "241", "name" => "Poco", "question_id" => " 112", ]);
        DB::table("answers_options")->insert([ "id" => "242", "name" => "Frecuente/M", "question_id" => " 112", ]);
        DB::table("answers_options")->insert([ "id" => "243", "name" => "Mucho", "question_id" => " 112", ]);
        DB::table("answers_options")->insert([ "id" => "244", "name" => "No", "question_id" => " 113", ]);
        DB::table("answers_options")->insert([ "id" => "245", "name" => "Poco", "question_id" => " 113", ]);
        DB::table("answers_options")->insert([ "id" => "246", "name" => "Frecuente/M", "question_id" => " 113", ]);
        DB::table("answers_options")->insert([ "id" => "247", "name" => "Mucho", "question_id" => " 113", ]);
        DB::table("answers_options")->insert([ "id" => "248", "name" => "No", "question_id" => " 114", ]);
        DB::table("answers_options")->insert([ "id" => "249", "name" => "Poco", "question_id" => " 114", ]);
        DB::table("answers_options")->insert([ "id" => "250", "name" => "Frecuente/M", "question_id" => " 114", ]);
        DB::table("answers_options")->insert([ "id" => "251", "name" => "Mucho", "question_id" => " 114", ]);
        DB::table("answers_options")->insert([ "id" => "252", "name" => "No", "question_id" => " 115", ]);
        DB::table("answers_options")->insert([ "id" => "253", "name" => "Poco", "question_id" => " 115", ]);
        DB::table("answers_options")->insert([ "id" => "254", "name" => "Frecuente/M", "question_id" => " 115", ]);
        DB::table("answers_options")->insert([ "id" => "255", "name" => "Mucho", "question_id" => " 115", ]);
        DB::table("answers_options")->insert([ "id" => "256", "name" => "No", "question_id" => " 116", ]);
        DB::table("answers_options")->insert([ "id" => "257", "name" => "Poco", "question_id" => " 116", ]);
        DB::table("answers_options")->insert([ "id" => "258", "name" => "Frecuente/M", "question_id" => " 116", ]);
        DB::table("answers_options")->insert([ "id" => "259", "name" => "Mucho", "question_id" => " 116", ]);
        DB::table("answers_options")->insert([ "id" => "260", "name" => "No", "question_id" => " 117", ]);
        DB::table("answers_options")->insert([ "id" => "261", "name" => "Poco", "question_id" => " 117", ]);
        DB::table("answers_options")->insert([ "id" => "262", "name" => "Frecuente/M", "question_id" => " 117", ]);
        DB::table("answers_options")->insert([ "id" => "263", "name" => "Mucho", "question_id" => " 117", ]);
        DB::table("answers_options")->insert([ "id" => "264", "name" => "No", "question_id" => " 118", ]);
        DB::table("answers_options")->insert([ "id" => "265", "name" => "Poco", "question_id" => " 118", ]);
        DB::table("answers_options")->insert([ "id" => "266", "name" => "Frecuente/M", "question_id" => " 118", ]);
        DB::table("answers_options")->insert([ "id" => "267", "name" => "Mucho", "question_id" => " 118", ]);
        DB::table("answers_options")->insert([ "id" => "268", "name" => "No", "question_id" => " 119", ]);
        DB::table("answers_options")->insert([ "id" => "269", "name" => "Poco", "question_id" => " 119", ]);
        DB::table("answers_options")->insert([ "id" => "270", "name" => "Frecuente/M", "question_id" => " 119", ]);
        DB::table("answers_options")->insert([ "id" => "271", "name" => "Mucho", "question_id" => " 119", ]);
        DB::table("answers_options")->insert([ "id" => "272", "name" => "No", "question_id" => " 120", ]);
        DB::table("answers_options")->insert([ "id" => "273", "name" => "Poco", "question_id" => " 120", ]);
        DB::table("answers_options")->insert([ "id" => "274", "name" => "Frecuente/M", "question_id" => " 120", ]);
        DB::table("answers_options")->insert([ "id" => "275", "name" => "Mucho", "question_id" => " 120", ]);
        DB::table("answers_options")->insert([ "id" => "276", "name" => "No", "question_id" => " 121", ]);
        DB::table("answers_options")->insert([ "id" => "277", "name" => "Poco", "question_id" => " 121", ]);
        DB::table("answers_options")->insert([ "id" => "278", "name" => "Frecuente/M", "question_id" => " 121", ]);
        DB::table("answers_options")->insert([ "id" => "279", "name" => "Mucho", "question_id" => " 121", ]);
        DB::table("answers_options")->insert([ "id" => "280", "name" => "No", "question_id" => " 122", ]);
        DB::table("answers_options")->insert([ "id" => "281", "name" => "Poco", "question_id" => " 122", ]);
        DB::table("answers_options")->insert([ "id" => "282", "name" => "Frecuente/M", "question_id" => " 122", ]);
        DB::table("answers_options")->insert([ "id" => "283", "name" => "Mucho", "question_id" => " 122", ]);
        DB::table("answers_options")->insert([ "id" => "284", "name" => "No", "question_id" => " 123", ]);
        DB::table("answers_options")->insert([ "id" => "285", "name" => "Poco", "question_id" => " 123", ]);
        DB::table("answers_options")->insert([ "id" => "286", "name" => "Frecuente/M", "question_id" => " 123", ]);
        DB::table("answers_options")->insert([ "id" => "287", "name" => "Mucho", "question_id" => " 123", ]);
        DB::table("answers_options")->insert([ "id" => "288", "name" => "No", "question_id" => " 124", ]);
        DB::table("answers_options")->insert([ "id" => "289", "name" => "Poco", "question_id" => " 124", ]);
        DB::table("answers_options")->insert([ "id" => "290", "name" => "Frecuente/M", "question_id" => " 124", ]);
        DB::table("answers_options")->insert([ "id" => "291", "name" => "Mucho", "question_id" => " 124", ]);
        DB::table("answers_options")->insert([ "id" => "292", "name" => "No", "question_id" => " 125", ]);
        DB::table("answers_options")->insert([ "id" => "293", "name" => "Poco", "question_id" => " 125", ]);
        DB::table("answers_options")->insert([ "id" => "294", "name" => "Frecuente/M", "question_id" => " 125", ]);
        DB::table("answers_options")->insert([ "id" => "295", "name" => "Mucho", "question_id" => " 125", ]);
        DB::table("answers_options")->insert([ "id" => "296", "name" => "Sí", "question_id" => " 138", ]);
        DB::table("answers_options")->insert([ "id" => "297", "name" => "No", "question_id" => " 138", ]);
        DB::table("answers_options")->insert([ "id" => "298", "name" => "Sí", "question_id" => " 149", ]);
        DB::table("answers_options")->insert([ "id" => "299", "name" => "No", "question_id" => " 148", ]);
        DB::table("answers_options")->insert([ "id" => "300", "name" => "Sí", "question_id" => " 150", ]);
        DB::table("answers_options")->insert([ "id" => "301", "name" => "No", "question_id" => " 150", ]);
        DB::table("answers_options")->insert([ "id" => "302", "name" => "Sí", "question_id" => " 151", ]);
        DB::table("answers_options")->insert([ "id" => "303", "name" => "No", "question_id" => " 151", ]);
        DB::table("answers_options")->insert([ "id" => "304", "name" => "Sí", "question_id" => " 152", ]);
        DB::table("answers_options")->insert([ "id" => "305", "name" => "No", "question_id" => " 152", ]);
        DB::table("answers_options")->insert([ "id" => "306", "name" => "Sí", "question_id" => " 153", ]);
        DB::table("answers_options")->insert([ "id" => "307", "name" => "No", "question_id" => " 153", ]);
        DB::table("answers_options")->insert([ "id" => "308", "name" => "Sí", "question_id" => " 154", ]);
        DB::table("answers_options")->insert([ "id" => "309", "name" => "No", "question_id" => " 154", ]);
        DB::table("answers_options")->insert([ "id" => "310", "name" => "Sí", "question_id" => " 155", ]);
        DB::table("answers_options")->insert([ "id" => "311", "name" => "No", "question_id" => " 155", ]);
        DB::table("answers_options")->insert([ "id" => "312", "name" => "Sí", "question_id" => " 156", ]);
        DB::table("answers_options")->insert([ "id" => "313", "name" => "No", "question_id" => " 156", ]);
        DB::table("answers_options")->insert([ "id" => "314", "name" => "Sí", "question_id" => " 157", ]);
        DB::table("answers_options")->insert([ "id" => "315", "name" => "No", "question_id" => " 157", ]);
        DB::table("answers_options")->insert([ "id" => "316", "name" => "Sí", "question_id" => " 158", ]);
        DB::table("answers_options")->insert([ "id" => "317", "name" => "No", "question_id" => " 158", ]);
        DB::table("answers_options")->insert([ "id" => "318", "name" => "Sí", "question_id" => " 159", ]);
        DB::table("answers_options")->insert([ "id" => "319", "name" => "No", "question_id" => " 159", ]);
        DB::table("answers_options")->insert([ "id" => "320", "name" => "Sí", "question_id" => " 160", ]);
        DB::table("answers_options")->insert([ "id" => "321", "name" => "No", "question_id" => " 160", ]);
        DB::table("answers_options")->insert([ "id" => "322", "name" => "Sí", "question_id" => " 161", ]);
        DB::table("answers_options")->insert([ "id" => "323", "name" => "No", "question_id" => " 161", ]);
        DB::table("answers_options")->insert([ "id" => "324", "name" => "Sí", "question_id" => " 162", ]);
        DB::table("answers_options")->insert([ "id" => "325", "name" => "No", "question_id" => " 162", ]);
        DB::table("answers_options")->insert([ "id" => "326", "name" => "Sí", "question_id" => " 163", ]);
        DB::table("answers_options")->insert([ "id" => "327", "name" => "No", "question_id" => " 163", ]);
        DB::table("answers_options")->insert([ "id" => "328", "name" => "Sí", "question_id" => " 164", ]);
        DB::table("answers_options")->insert([ "id" => "329", "name" => "No", "question_id" => " 164", ]);
        DB::table("answers_options")->insert([ "id" => "330", "name" => "Sí", "question_id" => " 165", ]);
        DB::table("answers_options")->insert([ "id" => "331", "name" => "No", "question_id" => " 165", ]);
        DB::table("answers_options")->insert([ "id" => "332", "name" => "Sí", "question_id" => " 166", ]);
        DB::table("answers_options")->insert([ "id" => "333", "name" => "No", "question_id" => " 166", ]);
        DB::table("answers_options")->insert([ "id" => "334", "name" => "Sí", "question_id" => " 167", ]);
        DB::table("answers_options")->insert([ "id" => "335", "name" => "No", "question_id" => " 167", ]);
        DB::table("answers_options")->insert([ "id" => "336", "name" => "Sí", "question_id" => " 168", ]);
        DB::table("answers_options")->insert([ "id" => "337", "name" => "No", "question_id" => " 168", ]);
        DB::table("answers_options")->insert([ "id" => "338", "name" => "Sí", "question_id" => " 169", ]);
        DB::table("answers_options")->insert([ "id" => "339", "name" => "No", "question_id" => " 169", ]);
        DB::table("answers_options")->insert([ "id" => "340", "name" => "Sí", "question_id" => " 170", ]);
        DB::table("answers_options")->insert([ "id" => "341", "name" => "No", "question_id" => " 170", ]);
        DB::table("answers_options")->insert([ "id" => "342", "name" => "Sí", "question_id" => " 171", ]);
        DB::table("answers_options")->insert([ "id" => "343", "name" => "No", "question_id" => " 171", ]);
        DB::table("answers_options")->insert([ "id" => "344", "name" => "Sí", "question_id" => " 172", ]);
        DB::table("answers_options")->insert([ "id" => "345", "name" => "No", "question_id" => " 172", ]);
        DB::table("answers_options")->insert([ "id" => "346", "name" => "Sí", "question_id" => " 173", ]);
        DB::table("answers_options")->insert([ "id" => "347", "name" => "No", "question_id" => " 173", ]);
        DB::table("answers_options")->insert([ "id" => "348", "name" => "Sí", "question_id" => " 174", ]);
        DB::table("answers_options")->insert([ "id" => "349", "name" => "No", "question_id" => " 174", ]);
        DB::table("answers_options")->insert([ "id" => "350", "name" => "Sí", "question_id" => " 175", ]);
        DB::table("answers_options")->insert([ "id" => "351", "name" => "No", "question_id" => " 175", ]);
        DB::table("answers_options")->insert([ "id" => "352", "name" => "Sí", "question_id" => " 176", ]);
        DB::table("answers_options")->insert([ "id" => "353", "name" => "No", "question_id" => " 176", ]);
        DB::table("answers_options")->insert([ "id" => "354", "name" => "Sí", "question_id" => " 177", ]);
        DB::table("answers_options")->insert([ "id" => "355", "name" => "No", "question_id" => " 177", ]);
        DB::table("answers_options")->insert([ "id" => "356", "name" => "Sí", "question_id" => " 178", ]);
        DB::table("answers_options")->insert([ "id" => "357", "name" => "No", "question_id" => " 178", ]);
        DB::table("answers_options")->insert([ "id" => "358", "name" => "Sí", "question_id" => " 179", ]);
        DB::table("answers_options")->insert([ "id" => "359", "name" => "No", "question_id" => " 179", ]);
        DB::table("answers_options")->insert([ "id" => "360", "name" => "Sí", "question_id" => " 180", ]);
        DB::table("answers_options")->insert([ "id" => "361", "name" => "No", "question_id" => " 180", ]);
        DB::table("answers_options")->insert([ "id" => "362", "name" => "Sí", "question_id" => " 181", ]);
        DB::table("answers_options")->insert([ "id" => "363", "name" => "No", "question_id" => " 181", ]);
        DB::table("answers_options")->insert([ "id" => "364", "name" => "Sí", "question_id" => " 182", ]);
        DB::table("answers_options")->insert([ "id" => "365", "name" => "No", "question_id" => " 182", ]);
        DB::table("answers_options")->insert([ "id" => "366", "name" => "Sí", "question_id" => " 183", ]);
        DB::table("answers_options")->insert([ "id" => "367", "name" => "No", "question_id" => " 183", ]);
        DB::table("answers_options")->insert([ "id" => "368", "name" => "Sí", "question_id" => " 184", ]);
        DB::table("answers_options")->insert([ "id" => "369", "name" => "No", "question_id" => " 184", ]);
        DB::table("answers_options")->insert([ "id" => "370", "name" => "Sí", "question_id" => " 185", ]);
        DB::table("answers_options")->insert([ "id" => "371", "name" => "No", "question_id" => " 185", ]);
        DB::table("answers_options")->insert([ "id" => "372", "name" => "Sí", "question_id" => " 186", ]);
        DB::table("answers_options")->insert([ "id" => "373", "name" => "No", "question_id" => " 186", ]);
        DB::table("answers_options")->insert([ "id" => "374", "name" => "Sí", "question_id" => " 187", ]);
        DB::table("answers_options")->insert([ "id" => "375", "name" => "No", "question_id" => " 187", ]);
        DB::table("answers_options")->insert([ "id" => "376", "name" => "Sí", "question_id" => " 188", ]);
        DB::table("answers_options")->insert([ "id" => "377", "name" => "No", "question_id" => " 188", ]);
        DB::table("answers_options")->insert([ "id" => "378", "name" => "Sí", "question_id" => " 189", ]);
        DB::table("answers_options")->insert([ "id" => "379", "name" => "No", "question_id" => " 189", ]);
        DB::table("answers_options")->insert([ "id" => "380", "name" => "Sí", "question_id" => " 190", ]);
        DB::table("answers_options")->insert([ "id" => "381", "name" => "No", "question_id" => " 190", ]);
        DB::table("answers_options")->insert([ "id" => "382", "name" => "Sí", "question_id" => " 191", ]);
        DB::table("answers_options")->insert([ "id" => "383", "name" => "No", "question_id" => " 191", ]);
        DB::table("answers_options")->insert([ "id" => "384", "name" => "Sí", "question_id" => " 192", ]);
        DB::table("answers_options")->insert([ "id" => "385", "name" => "No", "question_id" => " 192", ]);
        DB::table("answers_options")->insert([ "id" => "386", "name" => "Sí", "question_id" => " 193", ]);
        DB::table("answers_options")->insert([ "id" => "387", "name" => "No", "question_id" => " 193", ]);
        DB::table("answers_options")->insert([ "id" => "388", "name" => "Sí", "question_id" => " 194", ]);
        DB::table("answers_options")->insert([ "id" => "389", "name" => "No", "question_id" => " 194", ]);
        DB::table("answers_options")->insert([ "id" => "390", "name" => "Sí", "question_id" => " 195", ]);
        DB::table("answers_options")->insert([ "id" => "391", "name" => "No", "question_id" => " 195", ]);
        DB::table("answers_options")->insert([ "id" => "392", "name" => "Sí", "question_id" => " 196", ]);
        DB::table("answers_options")->insert([ "id" => "393", "name" => "No", "question_id" => " 196", ]);
        DB::table("answers_options")->insert([ "id" => "394", "name" => "Sí", "question_id" => " 197", ]);
        DB::table("answers_options")->insert([ "id" => "395", "name" => "No", "question_id" => " 197", ]);
        DB::table("answers_options")->insert([ "id" => "396", "name" => "Sí", "question_id" => " 198", ]);
        DB::table("answers_options")->insert([ "id" => "397", "name" => "No", "question_id" => " 198", ]);
        DB::table("answers_options")->insert([ "id" => "398", "name" => "Sí", "question_id" => " 200", ]);
        DB::table("answers_options")->insert([ "id" => "399", "name" => "No", "question_id" => " 199", ]);
        DB::table("answers_options")->insert([ "id" => "400", "name" => "Sí", "question_id" => " 200", ]);
        DB::table("answers_options")->insert([ "id" => "401", "name" => "No", "question_id" => " 200", ]);
        DB::table("answers_options")->insert([ "id" => "402", "name" => "Sí", "question_id" => " 201", ]);
        DB::table("answers_options")->insert([ "id" => "403", "name" => "No", "question_id" => " 201", ]);
        DB::table("answers_options")->insert([ "id" => "404", "name" => "Sí", "question_id" => " 202", ]);
        DB::table("answers_options")->insert([ "id" => "405", "name" => "No", "question_id" => " 202", ]);
        DB::table("answers_options")->insert([ "id" => "406", "name" => "Sí", "question_id" => " 203", ]);
        DB::table("answers_options")->insert([ "id" => "407", "name" => "No", "question_id" => " 203", ]);
        DB::table("answers_options")->insert([ "id" => "408", "name" => "Sí", "question_id" => " 204", ]);
        DB::table("answers_options")->insert([ "id" => "409", "name" => "No", "question_id" => " 204", ]);
        DB::table("answers_options")->insert([ "id" => "410", "name" => "Sí", "question_id" => " 205", ]);
        DB::table("answers_options")->insert([ "id" => "411", "name" => "No", "question_id" => " 205", ]);
        DB::table("answers_options")->insert([ "id" => "412", "name" => "Sí", "question_id" => " 206", ]);
        DB::table("answers_options")->insert([ "id" => "413", "name" => "No", "question_id" => " 206", ]);
        DB::table("answers_options")->insert([ "id" => "414", "name" => "Sí", "question_id" => " 207", ]);
        DB::table("answers_options")->insert([ "id" => "415", "name" => "No", "question_id" => " 207", ]);
        DB::table("answers_options")->insert([ "id" => "416", "name" => "Sí", "question_id" => " 208", ]);
        DB::table("answers_options")->insert([ "id" => "417", "name" => "No", "question_id" => " 208", ]);
        DB::table("answers_options")->insert([ "id" => "418", "name" => "No, consideras que tu opinión sea buena y que la de los demás no tenga por qué serlo siempre.", "question_id" => " 209", ]);
        DB::table("answers_options")->insert([ "id" => "419", "name" => "Sí, pero sólo ante las decisiones que consideras demasiado importantes como para actuar precipitadamente. ", "question_id" => " 209", ]);
        DB::table("answers_options")->insert([ "id" => "420", "name" => "Sí, siempre que puedes consultas con los demás. Te equivocas con frecuencia y quieres hacer las cosas bien.", "question_id" => " 209", ]);
        DB::table("answers_options")->insert([ "id" => "421", "name" => "Depende de la decisión. Sueles tener claro lo que vas a hacer, pero consideras las posibilidades que te ofrecen los demas.", "question_id" => " 209", ]);
        DB::table("answers_options")->insert([ "id" => "422", "name" => "No le das importancia, te comportas con naturalidad y si alguien te lo comenta haces alguna broma al respecto.", "question_id" => " 210", ]);
        DB::table("answers_options")->insert([ "id" => "423", "name" => "Te da mucha vergüenza. Procuras situarte en algún lugar discreto y pasar desapercibido. ", "question_id" => " 210", ]);
        DB::table("answers_options")->insert([ "id" => "424", "name" => "Te sientes incómodo pero tratas de no pensar en ello, te enteras en la reunión y das alguna excusa por tu error.", "question_id" => " 210", ]);
        DB::table("answers_options")->insert([ "id" => "425", "name" => "No te importa nada en absoluto, aunque no lleves la ropa adecuada tienes estil y sabes llevar bien cualquier cosa.", "question_id" => " 210", ]);
        DB::table("answers_options")->insert([ "id" => "426", "name" => "Admiras el estilo de tu acompañante, al final compras un par de prendas necesarias por muy simples en cuanto a forma y color.", "question_id" => " 211", ]);
        DB::table("answers_options")->insert([ "id" => "427", "name" => "No estás dispuesto a que te gane, decides comprar varias prendas muy modernas y bastante caras.", "question_id" => " 211", ]);
        DB::table("answers_options")->insert([ "id" => "428", "name" => "Asmiras su estilo pero eres muy consciente del tuyo, compras la ropa que mejor te sienta y que necesitas, y pasan un rato ameno probándolos cosas diferentes. ", "question_id" => " 211", ]);
        DB::table("answers_options")->insert([ "id" => "429", "name" => "A su lado te sientes bastante poca cosa, te quita las ganas de probarte nada y mucho menos de comprar. Pones una excusa y te marchas.", "question_id" => " 211", ]);
        DB::table("answers_options")->insert([ "id" => "430", "name" => "No crees que tengas mucho que contar, tu trabajo es muy corriente, tus amigos normalesi y aficiones también. Prefieres que esta persona te cuente su vida.", "question_id" => " 212", ]);
        DB::table("answers_options")->insert([ "id" => "431", "name" => "Tu trabajo te gusta y aunque sea corriente, siempre lo enfocas desde una perspectiva interesante, tus aficiones son tu pasión y disfrutas hablando de ellas, tambien hablas de tus proyectos futuros. ", "question_id" => " 212", ]);
        DB::table("answers_options")->insert([ "id" => "432", "name" => "Hablas en lineas generales de tu tabajo y de tus aficiones, sobre todo hablas de tus amigos y de lo más interesante de sus vidas", "question_id" => " 212", ]);
        DB::table("answers_options")->insert([ "id" => "433", "name" => "Más que tu trabajo actual, hablas de tus proyectos y de tus objetivos, y de lo que vas a hacer para logrados, de lo buenas que son tus amistades y lo poco usual de tus aficiones. Te gusta hablar de ti.", "question_id" => " 212", ]);
        DB::table("answers_options")->insert([ "id" => "434", "name" => "Paras la explicación y requieres que se empiece de nuevo, si tu no lo entiendes habrá muchas gente que tampoco lo haga.", "question_id" => " 213", ]);
        DB::table("answers_options")->insert([ "id" => "435", "name" => "Si hay más gente que pregunte tú también lo haces, si no, buscas en un aparte al ponente para que te aclare las dudas.", "question_id" => " 213", ]);
        DB::table("answers_options")->insert([ "id" => "436", "name" => "Te da mucha vergüenza preguntar y demostrar así que no entiendes. Más tarde preguntarás a algún amigo o intentarás informante por tu cuenta.", "question_id" => " 213", ]);
        DB::table("answers_options")->insert([ "id" => "437", "name" => "Tomas nota de lo que no entiendes para preguntarlo al finalizar la charla, si sigues con dudas perdirás información complementaria para prepararte mejor.", "question_id" => " 213", ]);
        DB::table("answers_options")->insert([ "id" => "438", "name" => "Satisfactoria, tratas de buscar el lado positivo de las cosas y nunca te faltan proyectos y objetivos que perseguir.", "question_id" => " 214", ]);
        DB::table("answers_options")->insert([ "id" => "439", "name" => "Horrible, no obstante, sabes que las cosas están mal y que tienes que aguantar lo que sea. Estás muy agradecido por tener trabajo.", "question_id" => " 214", ]);
        DB::table("answers_options")->insert([ "id" => "440", "name" => "No te prpeocupa especialmente el tema, tienes un montón de proyectos más importantes y con tu valía los alcanzarás.", "question_id" => " 214", ]);
        DB::table("answers_options")->insert([ "id" => "441", "name" => "Has logrado que no te afecte, consideras más importante tu vida personal y privada y eso es por lo que luchas.", "question_id" => " 214", ]);
        DB::table("answers_options")->insert([ "id" => "442", "name" => "Prefieres no pensarlo, el dia ha sido duro pero para ti no es algo nuevo, solo pides poder dormir bien y que mañana sea un día más tranquilo.", "question_id" => " 215", ]);
        DB::table("answers_options")->insert([ "id" => "443", "name" => "Se lo cuentas a todo el mundo, te gusta que se te reconozca cuando haces las cosas bien y exiges en cada que te mimen por haberte esforzado tanto.", "question_id" => " 215", ]);
        DB::table("answers_options")->insert([ "id" => "444", "name" => "Esás muy satisgecho y decides darte un capricho, darte un baño de espuma y ver una buena película, o comparte un regalito que hace tiempo querías.", "question_id" => " 215", ]);
        DB::table("answers_options")->insert([ "id" => "445", "name" => "Te preocupa que se te haya olvidado algo o haber hecho algo mal por la prisa, repasas mentalmente las actividades y al día siguiente esperas no tener queja de nadie.", "question_id" => " 215", ]);
        DB::table("answers_options")->insert([ "id" => "446", "name" => "No te planteas ser voluntario, hay mil personas más capacitadas que tú para la demostración y no se te da bien hablaren público.", "question_id" => " 216", ]);
        DB::table("answers_options")->insert([ "id" => "447", "name" => "Te presentas voluntario, puede ser una experiencia interesante y si sales elegido puedes hacer una presentación innovadora.", "question_id" => " 216", ]);
        DB::table("answers_options")->insert([ "id" => "448", "name" => "No te presentas, serías capaz de hacerla bien pero crees que hay gente mejor preparada y más original que tú.", "question_id" => " 216", ]);
        DB::table("answers_options")->insert([ "id" => "449", "name" => "Te presentas y estás casi seguro de que te elegirán, haces buenos proyectos y darás una buena imagen de la empresa.", "question_id" => " 216", ]);
        DB::table("answers_options")->insert([ "id" => "450", "name" => "La buena suerte puede tocarle a todo el mundo, yo me considero una persona afortunada a la que la vida le sonríe.", "question_id" => " 217", ]);
        DB::table("answers_options")->insert([ "id" => "451", "name" => "Para tener buena suerte hay que trabajar duro, sólo los muy afortunados la tienen sin apenas esfuerzo.", "question_id" => " 217", ]);
        DB::table("answers_options")->insert([ "id" => "452", "name" => "Yo no tengo suerte, tanto los premios como las cosas especia les sólo les pasan a los demás.", "question_id" => " 217", ]);
        DB::table("answers_options")->insert([ "id" => "453", "name" => "La suerte respecto a los premios es una cuestión de probabilidad, y respecto a las cosas de la vida, siempre depende de cómo se perciban.", "question_id" => " 217", ]);
        DB::table("answers_options")->insert([ "id" => "454", "name" => "Te interesa conocerlos no sólo para pasar un buen rato en la reunión sino porque puede ser una forma de iniciar una amistad. ", "question_id" => " 218", ]);
        DB::table("answers_options")->insert([ "id" => "455", "name" => "Esperas causarles una buena impresión y decir cosas que les puedan interesar. ", "question_id" => " 218", ]);
        DB::table("answers_options")->insert([ "id" => "456", "name" => "Te gustaría llevarles a tu terreno en la conversación para así poder hablar de los temas que más te interesan.", "question_id" => " 218", ]);
        DB::table("answers_options")->insert([ "id" => "457", "name" => "Antes de iniciar una conversación escuchas lo que dicen, y es peras para hablar a que lo hagan de temas que tú conozcas.", "question_id" => " 218", ]);        
        DB::table("answers_options")->insert([ "id" => "458", "name" => "Con frecuencia", "question_id" => " 219", ]);
        DB::table("answers_options")->insert([ "id" => "459", "name" => "De vez en cuando", "question_id" => " 219", ]);
        DB::table("answers_options")->insert([ "id" => "460", "name" => "Casi nunca", "question_id" => " 219", ]);
        DB::table("answers_options")->insert([ "id" => "461", "name" => "Nunca", "question_id" => " 219", ]);
        DB::table("answers_options")->insert([ "id" => "462", "name" => "Con frecuencia", "question_id" => " 220", ]);
        DB::table("answers_options")->insert([ "id" => "463", "name" => "De vez en cuando", "question_id" => " 220", ]);
        DB::table("answers_options")->insert([ "id" => "464", "name" => "Casi nunca", "question_id" => " 220", ]);
        DB::table("answers_options")->insert([ "id" => "465", "name" => "Nunca", "question_id" => " 220", ]);
        DB::table("answers_options")->insert([ "id" => "466", "name" => "Con frecuencia", "question_id" => " 221", ]);
        DB::table("answers_options")->insert([ "id" => "467", "name" => "De vez en cuando", "question_id" => " 221", ]);
        DB::table("answers_options")->insert([ "id" => "468", "name" => "Casi nunca", "question_id" => " 221", ]);
        DB::table("answers_options")->insert([ "id" => "469", "name" => "Nunca", "question_id" => " 221", ]);
        DB::table("answers_options")->insert([ "id" => "470", "name" => "Con frecuencia", "question_id" => " 222", ]);
        DB::table("answers_options")->insert([ "id" => "471", "name" => "De vez en cuando", "question_id" => " 222", ]);
        DB::table("answers_options")->insert([ "id" => "472", "name" => "Casi nunca", "question_id" => " 222", ]);
        DB::table("answers_options")->insert([ "id" => "473", "name" => "Nunca", "question_id" => " 222", ]);
        DB::table("answers_options")->insert([ "id" => "474", "name" => "Con frecuencia", "question_id" => " 223", ]);
        DB::table("answers_options")->insert([ "id" => "475", "name" => "De vez en cuando", "question_id" => " 223", ]);
        DB::table("answers_options")->insert([ "id" => "476", "name" => "Casi nunca", "question_id" => " 223", ]);
        DB::table("answers_options")->insert([ "id" => "477", "name" => "Nunca", "question_id" => " 223", ]);
        DB::table("answers_options")->insert([ "id" => "478", "name" => "Con frecuencia", "question_id" => " 224", ]);
        DB::table("answers_options")->insert([ "id" => "479", "name" => "De vez en cuando", "question_id" => " 224", ]);
        DB::table("answers_options")->insert([ "id" => "480", "name" => "Casi nunca", "question_id" => " 224", ]);
        DB::table("answers_options")->insert([ "id" => "481", "name" => "Nunca", "question_id" => " 224", ]);
        DB::table("answers_options")->insert([ "id" => "482", "name" => "Con frecuencia", "question_id" => " 225", ]);
        DB::table("answers_options")->insert([ "id" => "483", "name" => "De vez en cuando", "question_id" => " 225", ]);
        DB::table("answers_options")->insert([ "id" => "484", "name" => "Casi nunca", "question_id" => " 225", ]);
        DB::table("answers_options")->insert([ "id" => "485", "name" => "Nunca", "question_id" => " 225", ]);
        DB::table("answers_options")->insert([ "id" => "486", "name" => "Con frecuencia", "question_id" => " 226", ]);
        DB::table("answers_options")->insert([ "id" => "487", "name" => "De vez en cuando", "question_id" => " 226", ]);
        DB::table("answers_options")->insert([ "id" => "488", "name" => "Casi nunca", "question_id" => " 226", ]);
        DB::table("answers_options")->insert([ "id" => "489", "name" => "Nunca", "question_id" => " 226", ]);
        DB::table("answers_options")->insert([ "id" => "490", "name" => "Con frecuencia", "question_id" => " 227", ]);
        DB::table("answers_options")->insert([ "id" => "491", "name" => "De vez en cuando", "question_id" => " 227", ]);
        DB::table("answers_options")->insert([ "id" => "492", "name" => "Casi nunca", "question_id" => " 227", ]);
        DB::table("answers_options")->insert([ "id" => "493", "name" => "Nunca", "question_id" => " 227", ]);
        DB::table("answers_options")->insert([ "id" => "494", "name" => "Siempre", "question_id" => " 228", ]);
        DB::table("answers_options")->insert([ "id" => "495", "name" => "Casi siempre", "question_id" => " 228", ]);
        DB::table("answers_options")->insert([ "id" => "496", "name" => "A veces ", "question_id" => " 228", ]);
        DB::table("answers_options")->insert([ "id" => "497", "name" => "Casi nunca", "question_id" => " 228", ]);
        DB::table("answers_options")->insert([ "id" => "498", "name" => "Nunca", "question_id" => " 228", ]);
        DB::table("answers_options")->insert([ "id" => "499", "name" => "Siempre", "question_id" => " 229", ]);
        DB::table("answers_options")->insert([ "id" => "500", "name" => "Casi siempre", "question_id" => " 229", ]);
        DB::table("answers_options")->insert([ "id" => "501", "name" => "A veces ", "question_id" => " 229", ]);
        DB::table("answers_options")->insert([ "id" => "502", "name" => "Casi nunca", "question_id" => " 229", ]);
        DB::table("answers_options")->insert([ "id" => "503", "name" => "Nunca", "question_id" => " 229", ]);
        DB::table("answers_options")->insert([ "id" => "504", "name" => "Siempre", "question_id" => " 230", ]);
        DB::table("answers_options")->insert([ "id" => "505", "name" => "Casi siempre", "question_id" => " 230", ]);
        DB::table("answers_options")->insert([ "id" => "506", "name" => "A veces ", "question_id" => " 230", ]);
        DB::table("answers_options")->insert([ "id" => "507", "name" => "Casi nunca", "question_id" => " 230", ]);
        DB::table("answers_options")->insert([ "id" => "508", "name" => "Nunca", "question_id" => " 230", ]);
        DB::table("answers_options")->insert([ "id" => "509", "name" => "Siempre", "question_id" => " 231", ]);
        DB::table("answers_options")->insert([ "id" => "510", "name" => "Casi siempre", "question_id" => " 231", ]);
        DB::table("answers_options")->insert([ "id" => "511", "name" => "A veces ", "question_id" => " 231", ]);
        DB::table("answers_options")->insert([ "id" => "512", "name" => "Casi nunca", "question_id" => " 231", ]);
        DB::table("answers_options")->insert([ "id" => "513", "name" => "Nunca", "question_id" => " 231", ]);
        DB::table("answers_options")->insert([ "id" => "514", "name" => "Siempre", "question_id" => " 232", ]);
        DB::table("answers_options")->insert([ "id" => "515", "name" => "Casi siempre", "question_id" => " 232", ]);
        DB::table("answers_options")->insert([ "id" => "516", "name" => "A veces ", "question_id" => " 232", ]);
        DB::table("answers_options")->insert([ "id" => "517", "name" => "Casi nunca", "question_id" => " 232", ]);
        DB::table("answers_options")->insert([ "id" => "518", "name" => "Nunca", "question_id" => " 232", ]);
        DB::table("answers_options")->insert([ "id" => "519", "name" => "Siempre", "question_id" => " 233", ]);
        DB::table("answers_options")->insert([ "id" => "520", "name" => "Casi siempre", "question_id" => " 233", ]);
        DB::table("answers_options")->insert([ "id" => "521", "name" => "A veces ", "question_id" => " 233", ]);
        DB::table("answers_options")->insert([ "id" => "522", "name" => "Casi nunca", "question_id" => " 233", ]);
        DB::table("answers_options")->insert([ "id" => "523", "name" => "Nunca", "question_id" => " 233", ]);
        DB::table("answers_options")->insert([ "id" => "524", "name" => "Siempre", "question_id" => " 234", ]);
        DB::table("answers_options")->insert([ "id" => "525", "name" => "Casi siempre", "question_id" => " 234", ]);
        DB::table("answers_options")->insert([ "id" => "526", "name" => "A veces ", "question_id" => " 234", ]);
        DB::table("answers_options")->insert([ "id" => "527", "name" => "Casi nunca", "question_id" => " 234", ]);
        DB::table("answers_options")->insert([ "id" => "528", "name" => "Nunca", "question_id" => " 234", ]);
        DB::table("answers_options")->insert([ "id" => "529", "name" => "Siempre", "question_id" => " 235", ]);
        DB::table("answers_options")->insert([ "id" => "530", "name" => "Casi siempre", "question_id" => " 235", ]);
        DB::table("answers_options")->insert([ "id" => "531", "name" => "A veces ", "question_id" => " 235", ]);
        DB::table("answers_options")->insert([ "id" => "532", "name" => "Casi nunca", "question_id" => " 235", ]);
        DB::table("answers_options")->insert([ "id" => "533", "name" => "Nunca", "question_id" => " 235", ]);
        DB::table("answers_options")->insert([ "id" => "534", "name" => "Siempre", "question_id" => " 236", ]);
        DB::table("answers_options")->insert([ "id" => "535", "name" => "Casi siempre", "question_id" => " 236", ]);
        DB::table("answers_options")->insert([ "id" => "536", "name" => "A veces ", "question_id" => " 236", ]);
        DB::table("answers_options")->insert([ "id" => "537", "name" => "Casi nunca", "question_id" => " 236", ]);
        DB::table("answers_options")->insert([ "id" => "538", "name" => "Nunca", "question_id" => " 236", ]);
        DB::table("answers_options")->insert([ "id" => "539", "name" => "Siempre", "question_id" => " 237", ]);
        DB::table("answers_options")->insert([ "id" => "540", "name" => "Casi siempre", "question_id" => " 237", ]);
        DB::table("answers_options")->insert([ "id" => "541", "name" => "A veces ", "question_id" => " 237", ]);
        DB::table("answers_options")->insert([ "id" => "542", "name" => "Casi nunca", "question_id" => " 237", ]);
        DB::table("answers_options")->insert([ "id" => "543", "name" => "Nunca", "question_id" => " 237", ]);
        DB::table("answers_options")->insert([ "id" => "545", "name" => "Siempre", "question_id" => " 238", ]);
        DB::table("answers_options")->insert([ "id" => "546", "name" => "Casi siempre", "question_id" => " 238", ]);
        DB::table("answers_options")->insert([ "id" => "547", "name" => "A veces ", "question_id" => " 238", ]);
        DB::table("answers_options")->insert([ "id" => "548", "name" => "Casi nunca", "question_id" => " 238", ]);
        DB::table("answers_options")->insert([ "id" => "549", "name" => "Nunca", "question_id" => " 238", ]);
    }
}
